In [2]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [3]:
def stratified_sampling(df, genre_col, size_col, sample_size=0.5):
    df['계층_조합'] = df[genre_col].astype(str) + '_' + df[size_col].astype(str)
    stratified_sample, _ = train_test_split(
        df, 
        test_size=1-sample_size, 
        stratify=df['계층_조합']
    )
    
    return stratified_sample

In [5]:
for filename in os.listdir():
    if filename.endswith('.xlsx'):
        try:
            # 파일을 읽어보는 시도
            d = pd.read_excel(filename)
        except Exception as e:
            # 에러가 발생하면 파일 이름과 에러 메시지를 출력
            print(f"Error reading {filename}: {e}")

Error reading 2022_04_21_30_943,660.xlsx: Bad magic number for file header

In [4]:
df = pd.DataFrame()

for filename in os.listdir() :
    if filename.endswith('.xlsx') :
        d = pd.read_excel(filename)
        sampled_df = stratified_sampling(d, genre_col = '장르명', size_col = '극장규모')
        df = pd.concat([df, sampled_df], ignore_index=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12802173 entries, 0 to 12802172
Data columns (total 30 columns):
 #   Column           Dtype
---  ------           -----
 0   Unnamed: 0       int64
 1   좌석수              int64
 2   공연코드             object
 3   공연일시             object
 4   예매/취소일시          object
 5   예매/취소구분          int64
 6   예매/취소매수          int64
 7   예매/취소금액          float64
 8   예매/취소방식명(관리시스템)  object
 9   할인금액             int64
 10  할인종류명(전송처)       object
 11  장당금액             int64
 12  성별               int64
 13  연령               int64
 14  공연시작일자           object
 15  공연종료일자           object
 16  장르명              object
 17  공연지역명            object
 18  출연진내용            object
 19  아동공연 여부          object
 20  내한공연 여부          object
 21  오픈런 여부           object
 22  판매시작일시           object
 23  판매종료일시           object
 24  좌석등급             object
 25  극장규모             int64
 26  재관람              int64
 27  계층_조합            object
 28  공연회차             float64
 29  예매/취소방식명(전송처)    object
dtypes: float64(2), int64(10), object(18)
memory usage: 2.9+ GB

In [11]:
df.head()

,좌석수,공연코드,공연일시,예매/취소일시,예매/취소구분,예매/취소매수,예매/취소금액,예매/취소방식명(관리시스템),할인금액,할인종류명(전송처),...,아동공연 여부,내한공연 여부,오픈런 여부,판매시작일시,판매종료일시,좌석등급,극장규모,재관람,계층_조합,예매/취소방식명(전송처)
0,14,PF304959,2022-06-02 14:00,2022-05-02 09:38,1,1,69000.0,모바일,0,기타,...,N,N,Y,2021/11/01 00:00:00,9999/12/31 12:00:00,전석(69000),0,0,연극_0,NaN
1,365,PF300599,2022-06-09 20:00,2022-06-08 22:22,1,1,26400.0,웹,0,NaN,...,N,N,N,2022/04/21 11:00:00,2022/06/09 17:00:00,"R석(66000), S석(44000)",1,0,뮤지컬_1,NaN
2,250,PF390424,2022-06-05 17:00,2022-06-05 16:00,1,1,19000.0,모바일,16000,공연사 할인,...,N,N,Y,2021/06/02 11:20:00,2022/07/30 23:59:00,전석(35000),1,0,연극_1,NaN
3,1766,PF308077,2022-06-09 19:30,2022-05-24 09:56,1,1,135000.0,모바일,0,NaN,...,N,N,N,2022/04/05 14:00:00,2022/06/09 16:30:00,"VIP석(150000), R석(130000), S석(100000), A석(70000)",2,0,뮤지컬_2,NaN
4,622,PF308024,2022-06-04 18:00,2022-05-28 07:21,1,1,61600.0,모바일,0,NaN,...,N,N,N,2022/03/10 14:00:00,2022/06/11 11:00:00,"R석(77000), S석(55000)",1,0,뮤지컬_1,NaN

In [7]:
df = df.drop(columns='Unnamed: 0')

In [9]:
df['예매/취소방식명(전송처)'].unique()

array([nan, '티켓어플 아이폰', '웹', '모바일', '경기아트센터(web)', 'Web', '티켓모바일웹',
       '서울청년문화패스(mo)', '티켓링크앱', 'Olleh 공연(모바일)', '한국문화진흥원-컬쳐랜드(web)',
       '티켓어플 안드로이드', '모바일웹', '(주)인터파크 통합app', '기업할인_원더마미컴퍼니_mo',
       '티켓링크 모바일웹', '예매', 'KB_TEZE/ROVL(web)', '인터넷', '티켓링크웹', '인터넷(국문)',
       '서울청년문화패스(web)', 'NAVER', '기업할인_극단 명작옥수수밭4_mo', '기업할인_23삼총사(클립)',
       '정동극장(mobile)', '부평구문화재단(web)', '엔에이치엔(주)(네이버 지식쇼핑-web)',
       '공연장/구단 웹', '취소', '정동극장(web)', '기업할인_라이브러리컴퍼니2_mo', 'free',
       '해피머니 공연(web)', '재단법인 성남문화재단(web)', '기업할인_콘텐츠합_mo', '예술의전당(web)',
       '정동극장_기업할인10(MO)', 'PC', '기업할인_문화다방', '기업할인_카카오엔터테인먼트',
       '기업할인_글과무대2', '예술의전당(mobile)', '엔에이치엔(주)(네이버 지식쇼핑-모바일)',
       'Android(App)', '부평구문화재단(mobile)', '대전예술의전당(web)', 'KT 문화공연',
       '음성문화예술회관(web)', '신용카드', '음성문화예술회관(mobile)', '(재)두산연강재단(mobile)',
       '기업할인_(주)후플러스_mo', '기업할인_23삼총사(클립)2_mo', '카카오연동_공연', 'KAKAO',
       'iOS(App)', '기업할인_창작집단 농담1_mo', '기업할인_극단 지우9', '현대이지웰공연(web)',
       '기업할인_창작집단 농담1', '기업할인_랑2023_2mo', '기업할인_극단 명작옥수수밭6_mo',
       '두산연강재단_기업할인2(mo)', '기업할인_한국교직원공제회', '화성시문화재단(mobile)',
       '기업할인_문화다방_mo', '기업할인_라이브러리컴퍼니3_mo', '대전예술의전당(mobile)',
       '기업할인_한국연극인복지재단3', '인터넷(영문)', '기업할인_경기아트센터4(MO)', 'card',
       '기업할인_한국연극인복지재단3_mo', '기업할인_극단 명작옥수수밭6', '신한카드- 올댓컬쳐(모바일)',
       '기업할인_경기아트센터4(PC)', '현대이지웰공연(mobile)', '기업할인_여기는 당연히, 극장2_mo',
       '금천문화재단(mobile)', '기업할인_성북문화재단2(MO)', '정동극장_기업할인10',
       '기업할인_라이브러리컴퍼니7_mo', '기업할인_(주)후플러스', '기업할인_글과무대2_mo',
       '기업할인_주식회사 씨에이치수박3', '기업할인_카카오엔터테인먼트_mo', '경기아트센터(mobile)',
       '이제너두(web)', '기업할인_판_아이엠컬처_mo', '기업할인_판_아이엠컬처', '인터파크씨어터(web)',
       '(재)두산연강재단(web)', '기업할인_극단 무하_mo', '엔에이치엔(주)(네이버 바로가기-web)',
       '기업할인_극단 명작옥수수밭4', '기업할인_한국연극인복지재단2_mo', '화성시문화재단(web)',
       '정동극장_기업할인5', '두산연강재단_기업할인2', '금천문화재단(web)', '기업할인_주식회사 코스타2_mo',
       '기업할인_PH E＆M3_mo', '특정회원가격(Mobile)', '기업할인_주식회사 K.I ENT_mo',
       '기업할인_랑2023_3mo', 'vbank', '글로벌 웹', '재단법인 성남문화재단(mobile)',
       '기업할인_원더마미컴퍼니', '기업할인_나인진엔터테인먼트2_mo', '기업할인_시스터즈2_mo',
       '기업할인_시스터즈2', '기업할인_알앤디웍스_mo', '정동극장_기업할인6', '모바일웹앱',
       '(주)인터파크비즈마켓', '기업할인_경기아트센터8(PC)', '기업할인_라이브러리컴퍼니7', 'bank',
       '기업할인_라이브러리컴퍼니3', '정동극장_기업할인6(MO)', '기업할인_금천문화재단02(PC)',
       '기업할인_나인스토리_더쇼신라하다1p', '신한카드- 올댓컬쳐', '기업할인_컴인컴퍼니3_mo',
       '기업할인_크리에이티브테이블 석영_mo', '기업할인_성북문화재단2(PC)', '기업할인_주식회사 씨에이치수박3_mo',
       '기업할인_동국씨어터랩_mo', '광진문화재단(web)', '기업할인_2023 더블케이_mo',
       '기업할인_금천문화재단02(MO)', '예약', '기업할인_경기아트센터10(MO)', '기업할인_카카오엔터',
       '한국소리문화의전당(web)', '기업할인_23삼총사(클립)2', '해피포인트(SPC)_mobile',
       '기업할인_창작가무극 〈순신〉2_mo', '기업할인_한국연극인복지재단2', '(주)다음커뮤니케이션(쇼핑하우_모바일)',
       '부평구문화재단_직원할인50(mo)', '기업할인_(주)파크컴퍼니5_mo', '특정회원가격(web)',
       '기업할인_(재)영화의전당3(mo)', '기업할인_한국교직원공제회(mobile)',
       '부평구문화재단_직원할인50(pc)', '두산연강재단_기업할인', '기업할인_SK하이닉스', '기업할인_PH E＆M3',
       '(재)공주문화관광재단(web)', '기업할인_메타체인_mo', '기업할인_극단 지우3_mo',
       '기업할인_여기는 당연히, 극장2', '기업할인_(유)연극카지노_mo', '기업할인_라이브러리컴퍼니10',
       '기업할인_극단 지우3', '기업할인_2023 더블케이', '기업할인_나인스토리_더쇼신라하다2p',
       '기업할인_23삼총사(클립)4_mo', '(주)다음커뮤니케이션(쇼핑하우)', '기업할인_컴인컴퍼니3',
       '기업할인_(주)스포트라이트_mo', '기업할인_나인스토리_더쇼신라하다2m', '기업할인_창작가무극 〈순신〉2',
       '기업할인_주식회사 코스타2', '기업할인_(주)파크컴퍼니5', '기업할인_(주)NEO2_mo',
       '기업할인_극단 무하', '기업할인_(주)NEO2', '기업할인_SK하이닉스(mobile)', '기업할인_랑2023',
       '기업할인_랑2023_2', '기업할인_2023후크_mo', '기업할인_콘텐츠합', '기업할인_판_아이엠컬처2_mo',
       '기업할인_랑2023_3'], dtype=object)

In [10]:
df = df.drop(columns='공연회차')

In [12]:
df.to_csv('data_sample_0.5.csv')